import Providers from "@/providers/Providers.jsx";
import "./globals.css";

export const metadata = {
  title: "AmigosCharla",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"h-full"}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
